apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-ipv4: 35.240.84.74
    cloud.google.com/load-balancer-type: External
    meta.helm.sh/release-name: vault-eu-primary2
    meta.helm.sh/release-namespace: vault
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: vault-eu-primary
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.28.1
  name: vault-eu-primary2
  namespace: vault
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  loadBalancerIP: 35.240.84.74
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: https-internal
    port: 8201
    protocol: TCP
    targetPort: 8201
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: vault-eu-primary
    app.kubernetes.io/name: vault
    component: server
  sessionAffinity: None
  type: LoadBalancer
